spring.datasource.url=jdbc:h2:mem:hackhub
spring.datasource.driverClassName=org.h2.Driver
server.port=8080
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# Configurazione Gmail
gmail.enabled=false

#Variabili
hackathon.scadenza.giorni=14
invito.scadenza.giorni=3
crea.hack.giorni=14



