spring.datasource.url=jdbc:h2:file:./hackhub
spring.datasource.driverClassName=org.h2.Driver
server.port=8080
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true

# Configurazione Gmail
gmail.enabled=false

#Variabili
hackathon.scadenza.giorni=14
invito.scadenza.giorni=3
crea.hack.giorni=14



