# Abilita l'invio reale tramite Gmail API
gmail.enabled=true
GMAIL_CREDENTIALS_PATH=./secrets/credentials.json

# Gestione Forward Headers per Nginx Reverse Proxy
server.forward-headers-strategy=framework

# URL Frontend in produzione (HTTPS)
frontend.url=${FRONTEND_URL:https://35-181-19-124.sslip.io}

# Datasource MySQL
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:hackhub}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update